Update tcpping to allow the format of our tcptraceroute
linuxserver/docker-smokeping pull request #110
Opened 2021-03-17 05:17 UTC by eric

- [x] I have read the [contributing](https://github.com/linuxserver/docker-smokeping/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

The format of the tcptraceroute command does not seem to match what is expected by the tcpping.

It appears that tcpping was expected tcptraceroute was outputting the IP address within brackets but tcptraceroute is actually outputting the IP in parens.

## Benefits of this PR and context:

It seems to make tcpping actually work.

## How Has This Been Tested?

I've built the docker container locally and ran it and it displayed real numbers instead of always 255ms.

2021-03-18 00:17 UTC, Roxedus requested changes

2021-03-18 00:17 UTC, Roxedus commented on tcpping
> +        rtt=`echo "${ttr}" | sed 's/.*[])] //' | awk '{print $1}'`
revert this indentation

2022-10-04 13:40 UTC, ironicbadger commented
@eric is this abandoned?

2023-02-02 16:57 UTC, drizuid commented
closing due to no reply from OP

2023-02-02 16:57 UTC, closed without merging