Add configuration for running smokeping in slave mode
linuxserver/docker-smokeping pull request #170
Opened 2024-03-01 12:22 UTC by jkossis

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-smokeping/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

This change adds configuration (via environment variables) that allows for smokeping to be run in slave mode.

## Benefits of this PR and context:

Running smokeping in slave mode has its advantages, as you can define configuration that is the source-of-truth on the master host, and replicate it across different machines throughout your network. This can help tease out latency issues that may be unique to certain segments of the network.

## How Has This Been Tested?

This has been tested locally on my network. I built and ran the docker image locally on my slave host (raspberry pi 4b running on ubuntu server 22.04). Everything works as expected.

You just need to modify the slaves, targets, and slavessecrets file on the master host, per [the documentation](https://manpages.ubuntu.com/manpages/trusty/en/man7/smokeping_master_slave.7.html).

## Source / References:

2024-03-02 19:18 UTC, jkossis commented
@thespad @thelamer any chance I could get a review on this? 🙂

2024-03-15 18:33 UTC, thespad requested changes
Please add a changelog entry to the readme and then I'm happy to merge this

2024-03-22 18:59 UTC, jkossis commented
@thespad I updated the changelog, I appreciate you getting back to me on this.

2024-03-22 19:44 UTC, thespad approved these changes

2024-03-22 19:44 UTC, merged