add instructions for configuring the master-slave setup
linuxserver/docker-smokeping pull request #186
Opened 2024-12-27 04:52 UTC by zongsforce

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/docker-smokeping/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

## Benefits of this PR and context:

## How Has This Been Tested?

## Source / References:

2024-12-27 10:11 UTC, zongsforce commented
> Please note this part of the contribution document https://github.com/linuxserver/docker-smokeping/blob/master/.github/CONTRIBUTING.md#readme

The content I want to add is not compatible with the current YAML structure. Do I need to modify the code that generates the README? Could you please provide some suggestions?

Reasons for the conflict:
* hostname is an optional field, but it's not a variable under environment. At the same time, the meaning of the hostname parameter needs to be explained.
* The syntax generation for docker compose and docker run needs to be handled differently.

2024-12-27 10:14 UTC, Roxedus commented
These are the relevant variables for readme-vars https://github.com/linuxserver/docker-jenkins-builder/blob/b4796d74eef8d234fa6577696c2dd85720f895a5/vars/_container-vars-blank#L41-L43

2024-12-30 09:36 UTC, zongsforce commented
> These are the relevant variables for readme-vars https://github.com/linuxserver/docker-jenkins-builder/blob/b4796d74eef8d234fa6577696c2dd85720f895a5/vars/_container-vars-blank#L41-L43

I attempted to set the param_usage_include_hostname variable to true or 'optional', then locally rebuilt the Docker image and used docker run to regenerate the README.md. However, I found that the README.md still did not include the hostname variable (of course, I had already added the param_hostname variable to the readme-vars.yml file). Are these modification/testing steps expected to produce the desired outcome? If needed, I can provide all file changes and the Docker generation commands. Thanks for your patience.

Additionally, for testing purposes, I also tried setting the param_usage_include_vols and param_usage_include_ports variables to false, but it still did not change the generated content in the README.md.

2024-12-30 12:12 UTC, Roxedus commented
Generation works as expected. 
```sh
docker run --rm   \
  -v /git/lsio/docker-smokeping:/tmp \
  -e PUID=99 -e PGID=100 \
  lscr.io/linuxserver/jenkins-builder:latest
```


```diff
--- a/README.md
+++ b/README.md
@@ -82,6 +82,7 @@ services:
   smokeping:
     image: lscr.io/linuxserver/smokeping:latest
     container_name: smokeping
+    hostname: smokeping-main
     environment:
       - PUID=1000
       - PGID=1000
@@ -102,6 +103,7 @@ services:
 ```bash
 docker run -d \
   --name=smokeping \
+  --hostname=smokeping-main \
   -e PUID=1000 \
   -e PGID=1000 \
   -e TZ=Etc/UTC \
@@ -121,6 +123,7 @@ Containers are configured using parameters passed at runtime (such as those abov
 
 | Parameter | Function |
 | :----: | --- |
+| `--hostname=` | In a master-slave architecture, the hostname of the master node is displayed as its name in the web interface, while the hostname of the slave nodes represents their device aliases. These aliases must match the ones defined in the master's Slaves file. |
 | `-p 80:80` | Allows HTTP access to the internal webserver. |
 | `-e PUID=1000` | for UserID - see below for explanation |
 | `-e PGID=1000` | for GroupID - see below for explanation |
diff --git a/readme-vars.yml b/readme-vars.yml
index 4583d34..f16ec2f 100644
--- a/readme-vars.yml
+++ b/readme-vars.yml
@@ -24,6 +24,9 @@ opt_param_env_vars:
   - {env_var: "MASTER_URL", env_value: "http://<master-host-ip>:80/smokeping/", desc: "Specify the master url to connect to. Used when in slave mode."}
   - {env_var: "SHARED_SECRET", env_value: "password", desc: "Specify the master shared secret for this host. Used when in slave mode."}
   - {env_var: "CACHE_DIR", env_value: "/tmp", desc: "Specify the cache directory for this host. Used when in slave mode."}
+param_usage_include_hostname: true # you can set it to 'optional'
+param_hostname: "smokeping-main"
+param_hostname_desc: "In a master-slave architecture, the hostname of the master node is displayed as its name in the web interface, while the hostname of the slave nodes represents their device aliases. These aliases must match the ones defined in the master's Slaves file."
 # application setup block
 app_setup_block_enabled: true
 app_setup_block: |
```

2024-12-30 13:16 UTC, zongsforce commented
> Generation works as expected.
> 
> ```shell
> docker run --rm   \
>   -v /git/lsio/docker-smokeping:/tmp \
>   -e PUID=99 -e PGID=100 \
>   lscr.io/linuxserver/jenkins-builder:latest
> ```
> 
> ```diff
> --- a/README.md
> +++ b/README.md
> @@ -82,6 +82,7 @@ services:
>    smokeping:
>      image: lscr.io/linuxserver/smokeping:latest
>      container_name: smokeping
> +    hostname: smokeping-main
>      environment:
>        - PUID=1000
>        - PGID=1000
> @@ -102,6 +103,7 @@ services:
>  ```bash
>  docker run -d \
>    --name=smokeping \
> +  --hostname=smokeping-main \
>    -e PUID=1000 \
>    -e PGID=1000 \
>    -e TZ=Etc/UTC \
> @@ -121,6 +123,7 @@ Containers are configured using parameters passed at runtime (such as those abov
>  
>  | Parameter | Function |
>  | :----: | --- |
> +| `--hostname=` | In a master-slave architecture, the hostname of the master node is displayed as its name in the web interface, while the hostname of the slave nodes represents their device aliases. These aliases must match the ones defined in the master's Slaves file. |
>  | `-p 80:80` | Allows HTTP access to the internal webserver. |
>  | `-e PUID=1000` | for UserID - see below for explanation |
>  | `-e PGID=1000` | for GroupID - see below for explanation |
> diff --git a/readme-vars.yml b/readme-vars.yml
> index 4583d34..f16ec2f 100644
> --- a/readme-vars.yml
> +++ b/readme-vars.yml
> @@ -24,6 +24,9 @@ opt_param_env_vars:
>    - {env_var: "MASTER_URL", env_value: "http://<master-host-ip>:80/smokeping/", desc: "Specify the master url to connect to. Used when in slave mode."}
>    - {env_var: "SHARED_SECRET", env_value: "password", desc: "Specify the master shared secret for this host. Used when in slave mode."}
>    - {env_var: "CACHE_DIR", env_value: "/tmp", desc: "Specify the cache directory for this host. Used when in slave mode."}
> +param_usage_include_hostname: true # you can set it to 'optional'
> +param_hostname: "smokeping-main"
> +param_hostname_desc: "In a master-slave architecture, the hostname of the master node is displayed as its name in the web interface, while the hostname of the slave nodes represents their device aliases. These aliases must match the ones defined in the master's Slaves file."
>  # application setup block
>  app_setup_block_enabled: true
>  app_setup_block: |
> ```

It's done. There were some issues with my previous changes, but I've made a new commit and have already tested it. Please help me review the changes again. Thank you for your patient assistance.

2025-01-01 21:40 UTC, Roxedus requested changes

2025-01-01 21:40 UTC, Roxedus commented on readme-vars.yml
> +param_hostname: "hostname"
coming back to this after vacation, i think this should be `{{ project_name }}`, so it will be `smokeping` by default.

2025-01-02 08:47 UTC, zongsforce commented on readme-vars.yml
> +param_hostname: "hostname"
fine

2025-01-02 09:00 UTC, Roxedus approved these changes

2025-01-02 09:03 UTC, merged